=== eXplosive57/contributo-finale/storico_acq.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

  <xsd:element name="storico_acq">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="acq" maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="acq">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="id" />
        <xsd:element ref="id_utente"/>
        <xsd:element ref="nome_prodotto"/>
        <xsd:element ref="data_acquisto"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>


  <xsd:element name="id" type="integer" />
  <xsd:element name="id_utente" type="integer"/>
  <xsd:element name="nome_prodotto" type="string"/>
  <xsd:element name="data_acquisto" type="xs:date"/>

</xsd:schema>

=== eXplosive57/contributo-finale/storico_acq.xml
<?xml version="1.0" encoding="UTF-8"?>
<storico_acq xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="storico_acq.xsd">
  <acq>
    <id>1</id>
    <id_utente>15</id_utente>
    <nome_prodotto>Sansevieria</nome_prodotto>
    <data_acquisto>2023-11-26 19:48:01</data_acquisto>
  </acq>
  <acq>
    <id>2</id>
    <id_utente>15</id_utente>
    <nome_prodotto>Sansevieria</nome_prodotto>
    <data_acquisto>2023-11-26 19:50:57</data_acquisto>
  </acq>
</storico_acq>
