=== eXplosive57/contributo-finale/XML/faqs.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

  <xsd:element name="faqs">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="faq" maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="smartphone">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="id" />
        <xsd:element ref="domanda"/>
        <xsd:element ref="risposta"/>
        <xsd:element ref="creata_da"/>
        <xsd:element ref="data" />
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>


  <xsd:element name="id" type="integer" />
  <xsd:element name="domanda" type="string"/>
  <xsd:element name="risposta" type="string"/>
  <xsd:element name="creata_da" type="string"/>
  <xsd:element name="data" type="xs:date"/>

</xsd:schema>

=== eXplosive57/contributo-finale/XML/faqs.xml
<?xml version="1.0" encoding="UTF-8"?>
<faqs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="faqs.xsd">
  <faq>
    <id>1</id>
    <domanda>Quali sono le piante ideali per un ambiente con poca luce?</domanda>
    <risposta>Alcune piante adatte per ambienti con poca luce includono la Sansevieria, la Zamioculcas Zamiifolia (ZZ), e la Dracaena Marginata.</risposta>
    <creata_da>Fabio Mollura</creata_da>
    <data>2023-06-12</data>
  </faq>
  <faq>
    <id>2</id>
    <domanda>Come posso prendere cura delle piante grasse?</domanda>
    <risposta>Le piante grasse richiedono un terreno ben drenato, una luce solare diretta e innaffiature moderate. Assicurati che il vaso abbia fori di drenaggio e lascia asciugare completamente il terreno tra un\'innaffiatura e l\'altra.</risposta>
    <creata_da>Mario Rossi</creata_da>
    <data>2023-10-20</data>
  </faq>
  <faq>
    <id>3</id>
    <domanda>Quanto spesso dovrei innaffiare le mie piante d'appartamento?</domanda>
    <risposta>La frequenza di innaffiatura dipende dalla pianta e dalle condizioni ambientali. In linea di massima, aspetta che il terreno si asciughi leggermente prima di innaffiare.</risposta>
    <creata_da>Mario Rossi</creata_da>
    <data>2022-05-11</data>
  </faq>
  <faq>
    <id>4</id>
    <domanda>Come posso prevenire le malattie delle piante?</domanda>
    <risposta>Mantieni un\'adeguata circolazione d\'aria, evita il ristagno d\'acqua, pulisci regolarmente le foglie, e ispeziona le piante per rilevare eventuali segni di parassiti o malattie.</risposta>
    <creata_da>Luca Verdi</creata_da>
    <data>2022-02-21</data>
  </faq>
</faqs>
