=== eXplosive57/contributo-finale/XML/storico_cre.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

  <xsd:element name="storico_cre">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="richiesta" maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="richiesta">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="id" />
        <xsd:element ref="id_utente"/>
        <xsd:element ref="nome"/>
        <xsd:element ref="cognome"/>
        <xsd:element ref="qnt"/>
        <xsd:element ref="esito"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>


  <xsd:element name="id" type="integer" />
  <xsd:element name="id_utente" type="integer"/>
  <xsd:element name="nome" type="string"/>
  <xsd:element name="cognome" type="string"/>
  <xsd:element name="qnt" type="positiveInteger"/>
  <xsd:element name="id_utente" type="integer"/>

</xsd:schema>

=== eXplosive57/contributo-finale/XML/storico_cre.xml
<?xml version="1.0" encoding="UTF-8"?>
<storico_cre xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="storico_cre.xsd">
  <richiesta>
    <id>1</id>
    <id_utente>4</id_utente>
    <nome>Mario</nome>
    <cognome>Rossi</cognome>
    <qnt>20</qnt>
    <esito>1</esito>
  </richiesta>
  <richiesta>
    <id>2</id>
    <id_utente>3</id_utente>
    <nome>Luca</nome>
    <cognome>Verdi</cognome>
    <qnt>40</qnt>
    <esito>2</esito>
  </richiesta>
  <richiesta>
    <id>3</id>
    <id_utente>3</id_utente>
    <nome>Luca</nome>
    <cognome>Verdi</cognome>
    <qnt>90</qnt>
    <esito>1</esito>
  </richiesta>
  <richiesta>
    <id>4</id>
    <id_utente>5</id_utente>
    <nome>Fabio</nome>
    <cognome>Mollura</cognome>
    <qnt>25</qnt>
    <esito>2</esito>
  </richiesta>
  <richiesta>
    <id>5</id>
    <id_utente>5</id_utente>
    <nome>Fabio</nome>
    <cognome>Mollura</cognome>
    <qnt>45</qnt>
    <esito>0</esito>
  </richiesta>
  <richiesta>
    <id>6</id>
    <id_utente>5</id_utente>
    <nome>Fabio</nome>
    <cognome>Mollura</cognome>
    <qnt>70</qnt>
    <esito>1</esito>
  </richiesta>
  <richiesta>
    <id>7</id>
    <id_utente>3</id_utente>
    <nome>Luca</nome>
    <cognome>Verdi</cognome>
    <qnt>15</qnt>
    <esito>1</esito>
  </richiesta>
  <richiesta>
    <id>8</id>
    <id_utente>4</id_utente>
    <nome>Mario</nome>
    <cognome>Rossi</cognome>
    <qnt>250</qnt>
    <esito>2</esito>
  </richiesta>
  <richiesta>
    <id>9</id>
    <id_utente>4</id_utente>
    <nome>Mario</nome>
    <cognome>Rossi</cognome>
    <qnt>500</qnt>
    <esito>2</esito>
  </richiesta>
  <richiesta>
    <id>10</id>
    <id_utente>6</id_utente>
    <nome>Sara</nome>
    <cognome>Bernassola</cognome>
    <qnt>120</qnt>
    <esito>0</esito>
  </richiesta>
</storico_cre>

=== eXplosive57/contributo-finale/storico_cre.xml
<?xml version="1.0" encoding="UTF-8"?>
<storico_cre xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="storico_cre.xsd">
  <richiesta>
    <id>1</id>
    <id_utente>14</id_utente>
    <nome>Mario</nome>
    <cognome>Rossi</cognome>
    <qnt>23</qnt>
  </richiesta>
  <richiesta>
    <id>2</id>
    <id_utente>15</id_utente>
    <nome>Luca</nome>
    <cognome>Verdi</cognome>
    <qnt>44</qnt>
  </richiesta>
  <richiesta>
    <id>3</id>
    <id_utente>16</id_utente>
    <nome>Luigi</nome>
    <cognome>Lucio</cognome>
    <qnt>120</qnt>
  </richiesta>
</storico_cre>
